### PR TITLE
add github_version to package

### PR DESCRIPTION
**Pull request by jburel**
Add github_version to package section

### CODE REVIEW

**Review by sbesson — COMMENTED** [review]
https://github.com/ome/scc/pull/283#pullrequestreview-1389930699 was executed successfully against the current HEAD of this repository. What is the benefit/intent of this addition?

**Comment by jburel** [comment]
Mainly to keep things in synch

**Comment by sbesson** [comment]
Thanks. I suspect there is no harm in merging this  but I don't understand enough the implications registering additional keys in the `package` metadata so I'll defer to someone more knowledgeable.

**Comment by jburel** [comment]
Actually closing since ``package/top-level`` and ``package/tag`` are the other keys that we could consider

**Comment by jburel** [comment]
Actually I was incorrect, the value will not be set in the url if not defined but this is not what conda will expect.
since ``version`` and ``github_version`` are the same, I will recommend that we use only one variable. This means that the scc PR is relevant

**Comment by sbesson** [comment]
No objection here. The `github_version` variable was introduced specifically for testing release candidates due to the difference between semver (used by bioformats2raw) and pep440 (used by conda). If only final releases are considered moving forward, unifying the two variables certainly makes sense.

**Comment by jburel** [comment]
Merging so we can have the action green again

**Pull request merged**
